# Generated by Django 2.2.24 on 2022-03-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descriptio',
            new_name='description',
        ),
    ]
